### ISSUE TITLE
加载库报错

### ISSUE THREAD

**Issue by liang979zhang** [Sky24n/flustars#10]
![image](https://user-images.githubusercontent.com/16227667/58611558-223aa800-82e2-11e9-9598-65cb465da600.png)

**Comment by Sky24n** [comment]
我是基于beta分支开发的，当前最新v1.5.4-hotfix.2。
dev分支上最新1.6.3，这个版本的方法有变化导致不兼容。
我这边只有等beta分支升级后再修改。因为这个是最稳定的版本。

**Comment by Sky24n** [comment]
已修复。 
flustars: ^0.2.5+1

**Comment by didiaogithub** [comment]
<img width="573" alt="屏幕快照 2019-06-02 下午5 09 27" src="https://user-images.githubusercontent.com/20793564/58759229-3e944a00-8559-11e9-892a-77f7b6f0e506.png">

**Comment by zhanghuibiao** [comment]
同上
![image](https://user-images.githubusercontent.com/19171770/58771746-641c6480-85e8-11e9-97df-5acbfa4d425b.png)

**Comment by Sky24n** [comment]
flutter beta分支v1.5.4-hotfix.2，请用0.2.5版本。
flutter beta分支v1.6.3，请用0.2.5+1版本。

**Comment by itlws** [comment]
@Sky24n 楼主把flustars 类库中的 new ImageStreamLintenter去掉就可以了
[
![image](https://user-images.githubusercontent.com/7419461/59494949-dc283b80-8ec0-11e9-8da7-613c74750ec9.png)
](url)

**Comment by Sky24n** [comment]
flutter 1.6.3版本开始，这个方法就改变了导致的不兼容。升级到 1.6.3版本后就没有问题了。我是基于这个版本开发的。
```dart
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.503], locale zh-CN)

这是最新的源码。
class ImageStreamListener {
  /// Creates a new [ImageStreamListener].
  ///
  /// The [onImage] parameter must not be null.
  const ImageStreamListener(
    this.onImage, {
    this.onChunk,
    this.onError,
  }) : assert(onImage != null);
```

**Comment by certhon** [comment]
弱弱问一句 这个版本号在哪里改  yaml这个文件里好像没有看到这个widetutil

**Comment by Sky24n** [comment]
> 
> 
> 弱弱问一句 这个版本号在哪里改 yaml这个文件里好像没有看到这个widetutil

dependencies:
  flustars: ^0.2.6+1

**Comment by Kevin088** [comment]
flustars: ^0.2.6+1   版本
widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'.  还是报这个错

**Comment by Sky24n** [comment]
> 
> 
> flustars: ^0.2.6+1 版本
> widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'. 还是报这个错

上面说得那么清楚，还来问题！！！

**Comment by Kevin088** [comment]
这个版本  flustars: ^0.2.6+1  不是修复了这个问题吗   可是我还是出这个错 运行不起来

**Comment by Sky24n** [comment]
跟库没有任何关系，你flutter版本太低了，flutter 1.6.3版本开始，google官方改变的ImageStreamListener方法引起的不兼容，升级一下就好了！flutter upgrade
上面不是说的很清楚嘛！而且readme注意事项也有说明。

**Comment by Kevin088** [comment]
好的  没看明白 不好意思
