### ISSUE TITLE
添加flustars: ^0.2.5+1  cocoapods报错

### ISSUE THREAD

**Issue by HuTuXuZai** [Sky24n/flustars#12]
Launching lib/main.dart on iPod touch in debug mode...

Signing iOS app for device deployment using developer identity: "iPhone Developer: li pengfei (UGQ6C8DH5Y)"

CocoaPods' output:

↳

    [!] Invalid `Podfile` file: invalid byte sequence in US-ASCII.

     #  from /Users/xuzhao/Desktop/FLutterApp测试/zxeasynet_learn/ios/Podfile:21

     #  -------------------------------------------

     #    File.foreach(file_abs_path) { |line|

     >        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }

     #        plugin = line.split(pattern=separator)

     #  -------------------------------------------

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:50:in `initialize'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:293:in `new'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:293:in `from_ruby'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.7.2/lib/cocoapods-core/podfile.rb:259:in `from_file'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/lib/cocoapods/config.rb:199:in `podfile'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:45:in `run'

    /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'

    /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'

    /usr/local/bin/pod:23:in `load'

    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:

↳

        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.

        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8

        

Error running pod install

Exited (sigterm)

我当前的flutter版本是

localhost:~ xuzhao$ flutter --version
Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (4 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

**Comment by Sky24n** [comment]
跟我库好像没有多大关系。
1、用最新版 ^0.2.6+1 试试。
2、把你项目的中文去掉吧！

**Comment by HuTuXuZai** [comment]
> 跟我库好像没有多大关系。
> 1、用最新版 ^0.2.6+1 试试。
> 2、把你项目的中文去掉吧！

我项目中没有中文！那个FLutterApp测试 只是放在桌面上的文件夹，后面的zxeasynet_learn才是项目名， 这会有影响吗？

**Comment by HuTuXuZai** [comment]
改了一下， 就能运行了， 看来确实是这个原因！
