### ISSUE TITLE
升级到0.2.6报错了

### ISSUE THREAD

**Issue by HZRZCW** [Sky24n/flustars#14]
报错信息如下：
Compiler message:
file:///Users/zhangchangwei/Desktop/flutterWorkspace/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/zhangchangwei/Desktop/flutterWorkspace/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6/lib/src/widget_util.dart:88:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(

**Comment by Sky24n** [comment]
//切换到flutter beta分支
flutter channel beta
  
//升级
flutter upgrade

**Comment by HZRZCW** [comment]
我用稳定版不行？一定要beta分支？

**Comment by Sky24n** [comment]
flutter 最低版本1.6.3，随便你那个分支。

**Comment by uhua** [comment]
> 我用稳定版不行？一定要beta分支？

我也是用的稳定版,稳定版现在最高只有1.4还是1.5,要切换到beta或者dev分支才可以

**Comment by Sky24n** [comment]
早晚都要更新的，google官方在1.6.3变更的ImageStreamListener，等后面稳定版升级到1.6.3后，你现在的方法就会不兼容，原则上来说beta分支也属于稳定分支，没有什么好纠结的
