### ISSUE TITLE
ScreenUtil 最好能加个获取控制的位置

### ISSUE THREAD

**Issue by lifetin** [Sky24n/flustars#15]
GlobalObjectKey conTextKey = GlobalObjectKey('contenxt');

 RenderBox box = conTextKey.currentContext.findRenderObject();
  box.localToGlobal(Offset.zero)

这样能获取某个控制在页面,的具体位置,一般页面滚动到某个位置后,要去回到某个控制的位置上去,就得这么干,
不同于直接滚动到0,这是要滚动到不确定的位置
参考
https://blog.csdn.net/developer_zhao/article/details/86305463

**Comment by Sky24n** [comment]
这个很早就有了，在[WidgetUtil](https://github.com/Sky24n/flustars/blob/master/lib/src/widget_util.dart)里面。
