### ISSUE TITLE
https://github.com/Sky24n/common_utils

### ISSUE THREAD

**Issue by jp1017** [Sky24n/flustars#2]
https://github.com/Sky24n/common_utils

这俩项目啥关系呢，乱乱的

**Comment by Sky24n** [comment]
最开始是都common_utils里面，flustars是从里面拆出来的。
现在common_utils是纯dart包了。flustars是flutter相关的工具类包。

**Comment by jp1017** [comment]
flutter多久了，好厉害的

**Comment by Sky24n** [comment]
flutter玩了几个月了，相对规范完整项目[flutter_wanandroid](https://github.com/Sky24n/flutter_wanandroid)欢迎star。
