### ISSUE TITLE
为什么在flutter-wanandroid项目中没看到引入？

### ISSUE THREAD

**Issue by itshu** [Sky24n/flustars#22]
flutter-wanandroid使用的是：
base_library:
      git:
        url: git://github.com/Sky24n/FlutterRepos.git
        path: base_library

没看到有引入flustars的地方，为啥也不报错？

**Comment by Sky24n** [comment]
base_library 作为基础组件库，已经聚合了flustars

**Comment by itshu** [comment]
好的，多谢
