### ISSUE TITLE
iOS工程 archive 编译报错

### ISSUE THREAD

**Issue by OmgKevin** [Sky24n/flustars#23]
iOS工程里引入了flutter module模块，flutter module里用到了flustars: ^0.2.6+1 插件，xcode项目编译与运行正常，当xcode执行archive的时候编译报错，报错提示在path_provider库，报错内容如下：
/////////////////////////////////////
ld: warning: Could not find or use auto-linked framework 'Flutter'
Undefined symbols for architecture armv7:
  "_FlutterMethodNotImplemented", referenced from:
      ___47+[FLTPathProviderPlugin registerWithRegistrar:]_block_invoke in PathProviderPlugin.o
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in PathProviderPlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in PathProviderPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/////////////////////////////////////

Xcode版本：11.1
flutter版本：
[✓] Flutter (Channel master, v1.10.2-pre.4, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

我看您的这个插件中有引用到path_provider这个插件库，是不是什么原因导致的这个报错呢

**Comment by OmgKevin** [comment]
看起来报错好像跟运行架构有关，我这边的xcode 支持架构如下：

//:configuration = Debug
VALID_ARCHS = arm64 arm64e armv7 armv7s

//:configuration = Release
VALID_ARCHS = arm64 arm64e armv7 armv7s

//:completeSettings = some
VALID_ARCHS

**Comment by Sky24n** [comment]
iOS不懂，应该是你说的那个原因， 你可以看下这个。
[lutter默认引擎支持的cpu指令集](https://blog.csdn.net/langouster/article/details/90235230)
