### ISSUE TITLE
flutter 1.12.13+hotfix.5 编译报错

### ISSUE THREAD

**Issue by grapewheel** [Sky24n/flustars#24]
Could not compile build file '/opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/build.gradle'

**Comment by Sky24n** [comment]
哪一个flutter分支呢

**Comment by grapewheel** [comment]
master https://github.com/flutter/flutter/releases/tag/v1.12.13%2Bhotfix.5

**Comment by Sky24n** [comment]
我这边能正常运行，你把项目清除下，flutter clean试试
 Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)

**Comment by grapewheel** [comment]
flutter clean并重启后依然不行，我用的是 flustars 0.2.6+1

**Comment by Sky24n** [comment]
把.pub-cache/hosted/pub.dartlang.org文件夹下的path_provider库删除了，然后重新flutter packages get试试

**Comment by grapewheel** [comment]
我找到原因了，是由于jdk版本过高导致编译失败，flutter目前只能用1.8
