### ISSUE TITLE
WidgetUtil.getImageWH获取gif图片尺寸报错

### ISSUE THREAD

**Issue by 498619363** [Sky24n/flustars#25]
String _src="https://dsd361-oss1.oss-cn-beijing.aliyuncs.com/upload/advert/2d56ad78-472d-4eaf-b1f1-9a6887089d17.gif";

Rect rect2 = await WidgetUtil.getImageWH(url: _src);
![QQ截图20200111151848](https://user-images.githubusercontent.com/30884295/72200617-9e0aee80-3486-11ea-8197-0d601a8f5c9b.jpg)

**Comment by Sky24n** [comment]
fix
