### ISSUE TITLE
0.2.1+依赖好多

### ISSUE THREAD

**Issue by jp1017** [Sky24n/flustars#4]
>Because flutter_cache_manager 0.2.0+1 depends on shared_preferences ^0.4.0 and no versions of flutter_cache_manager match >0.2.0+1 <0.3.0, flutter_cache_manager ^0.2.0+1 requires shared_preferences ^0.4.0.
And because flustars >=0.2.1 depends on shared_preferences ^0.5.0, flustars >=0.2.1 is incompatible with flutter_cache_manager ^0.2.0+1.
And because cached_network_image 0.5.1 depends on flutter_cache_manager ^0.2.0+1 and no versions of cached_network_image match >0.5.1 <0.6.0, flustars >=0.2.1 is incompatible with cached_network_image ^0.5.1.
So, because module_flutter depends on both cached_network_image ^0.5.1 and flustars 0.2.2, version solving failed.
pub get failed (1)

降级为0.2.0版本啦

**Comment by Sky24n** [comment]
你用下最新版 0.2.3试试
