### ISSUE TITLE
文件操作工具类，创建文件一直不成功

### ISSUE THREAD

**Issue by Jacky-Xu** [Sky24n/flustars#41]
如： String apkPath = DirectoryUtil.getStoragePath(category:'Download',fileName: 'app_release',format: 'apk');
打印apkPath 一直返回是null?

**Comment by Sky24n** [comment]
这两句代码有运行过吗？？？
    setInitDir(initStorageDir: true);
    await DirectoryUtil.getInstance();

**Comment by Jacky-Xu** [comment]
@Sky24n   感谢作者，已解决了，必须要先setInit一下。 我看demo代码里面没有调用setInit。
