### ISSUE TITLE
SpUtil存的字段，在Android原生那边取不到。

### ISSUE THREAD

**Issue by WangPe1n** [Sky24n/flustars#42]
我想在APP启动的时候读取上次登录已经存在本地的userId和userName，但是获取这两个字段一直获取不到。
![image](https://user-images.githubusercontent.com/22020970/106247810-0754cf80-624b-11eb-95e8-88ec7e8e1912.png)

![image](https://user-images.githubusercontent.com/22020970/106247756-f1470f00-624a-11eb-8bfb-69f3078ea5be.png)

**Comment by Sky24n** [comment]
1.请确认在flutter值是否存成功，关闭app重新打开测试。
2.在MyApplication测试直接读取sp。
```
class MyApplication {
    private static final String SHARED_PREFERENCES_NAME = "FlutterSharedPreferences";
    private android.content.SharedPreferences _prefs;
    
    @Override
    public void onCreate() {
        super.onCreate();
        _prefs = this.getSharedPreferences(SHARED_PREFERENCES_NAME, Context.MODE_PRIVATE);
        sp.getString("flutter.user_name","");
    }
```

**Comment by WangPe1n** [comment]
好的  谢谢
