### ISSUE TITLE
flustars 2.0.1 Error

### ISSUE THREAD

**Issue by jianhuaz** [Sky24n/flustars#44]
await DirectoryUtil.getInstance();
DirectoryUtil.createStorageDirSync(category: 'apk');
String path = DirectoryUtil.getStoragePath(category: 'apk', fileName: 'pxt',  format: 'apk');
print("path::::${path}");

path = null
?

**Comment by Sky24n** [comment]
/// 配置初始化Directory。
void setInitDir(
