### ISSUE TITLE
初始化SpUtil.getInstance后提示Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by houkhan** [Sky24n/flustars#45]
初始化代码

void main() {
  _initApp();
  runApp(const MyApp());
}

_initApp() async {
  LogUtil.init(tag: GlobalAppData.appLogTag, isDebug: GlobalAppData.isDebug);
  await SpUtil.getInstance();
}

错误日志

E/flutter ( 2316): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 2316): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 2316): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 2316): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 2316): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
E/flutter ( 2316): #4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44:25)
E/flutter ( 2316): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:180:57)
E/flutter ( 2316): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:56:19)
E/flutter ( 2316): #7      SpUtil._init (package:sp_util/sp_util.dart:41:38)
E/flutter ( 2316): #8      SpUtil.getInstance.<anonymous closure> (package:sp_util/sp_util.dart:30:27)
E/flutter ( 2316): #9      SpUtil.getInstance.<anonymous closure> (package:sp_util/sp_util.dart:25:32)
E/flutter ( 2316): #10     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:24)
E/flutter ( 2316): #11     SpUtil.getInstance (package:sp_util/sp_util.dart:25:19)
E/flutter ( 2316): #12     _initApp (package:hello_flutter/main.dart:19:16)
E/flutter ( 2316): #13     main (package:hello_flutter/main.dart:11:3)
E/flutter ( 2316): #14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 2316): #15     _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 2316): #16     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 2316): #17     _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 2316): #18     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 2316): #19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 2316): #20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 2316): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

flustars版本 flustars: ^2.0.1

Flutter 版本 

Flutter 2.2.3 • channel stable • git@gitee.com:mirrors/Flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by Sky24n** [comment]
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SpUtil.getInstance();
  runApp(const MyApp());
}
```

**Comment by houkhan** [comment]
Ok 已解决
