### ISSUE TITLE
升级了Flutter，报错了。

### ISSUE THREAD

**Issue by HZRZCW** [Sky24n/flustars#49]
../../../../flutterWorkspace/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../../flutterWorkspace/flutter/.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
    return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
突然出现这种情况。。。。

**Comment by HZRZCW** [comment]
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)

**Comment by ConanXie** [comment]
在项目 pubspec.yaml 中指定 `decimal` 版本可以解决
```yaml
decimal: 1.5.0
```

**Comment by HZRZCW** [comment]
> 在项目 pubspec.yaml 中指定 `decimal` 版本可以解决
> 
> ```yaml
> decimal: 1.5.0
> ```

🐂

**Comment by kimiangel** [comment]
> 
在android上没有报错了，但是在ios上运行还是报错，大家有遇到吗，该怎么处理呢

**Comment by SECBoss** [comment]
同样情况，请作者尽快解决，谢谢！

**Comment by purgeyao** [comment]
同样问题 
```
Xcode's output:
↳
    ../../../Code/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
     - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../Code/flutter/.pub-cache/hosted/pub.dartlang.org/decimal-2.1.0/lib/decimal.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
        return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
                                                              ^^^^^
    ../../../Code/flutter/.pub-cache/hosted/pub.dartlang.org/common_utils-2.0.2/lib/src/num_util.dart:134:29: Error: A value of type 'Rational' can't be returned from a function with return type 'Decimal'.
     - 'Rational' is from 'package:rational/rational.dart' ('../../../Code/flutter/.pub-cache/hosted/pub.dartlang.org/rational-2.0.0/lib/rational.dart').
     - 'Decimal' is from 'package:decimal/decimal.dart' ('../../../Code/flutter/.pub-cache/hosted/pub.dartlang.org/decimal-2.1.0/lib/decimal.dart').
        return Decimal.parse(a) / Decimal.parse(b);
                                ^
```

**Comment by purgeyao** [comment]
@Sky24n  作者可以看看这个问题么  最新版本` flustars: ^2.0.1`

**Comment by Sky24n** [comment]
common_utils: ^2.1.0
