### ISSUE TITLE
flutter 1.6.3 出错

### ISSUE THREAD

**Issue by unreal0** [Sky24n/flustars#8]
widget_util.dart:115:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
       ^^^^^^^
Compiler failed on /Users/unreal/Downloads/flutter/lib/main.dart
Gradle task assembleDebug failed with exit code 1

**Comment by Sky24n** [comment]
我是基于beta分支开发的，当前最新v1.5.4-hotfix.2。
dev分支上最新1.6.3，这个版本的方法有变化导致不兼容。
我这边只有等beta分支升级后再修改。因为这个是最稳定的版本。

**Comment by sky126** [comment]
img.image.resolve(new ImageConfiguration()).addListener(ImageStreamListener((ImageInfo info, bool synchronous) {
       completer.complete(Rect.fromLTWH(
          0, 0, info.image.width.toDouble(), info.image.height.toDouble()));
    }, onError: (dynamic exception, StackTrace stackTrace) {
    completer.completeError(exception, stackTrace);
    }));

**Comment by Sky24n** [comment]
已修复。 
flustars: ^0.2.5+1
