### ISSUE TITLE
关于SpUtil的初始化，在闪屏页延迟500毫秒就一定能加载完吗？

### ISSUE THREAD

**Issue by bjxiaowanzi** [Sky24n/flustars#9]
你好，我是flutter新手，查本地存储的时候查到的这个库。发现里面关于异步读取本地存储的代码：
`Future.delayed(new Duration(milliseconds: 500), () {
      /// 同步使用Sp。
      /// 是否显示引导页。
      if (SpUtil.getBool("key_guide", defValue: true)) {
        SpUtil.putBool("key_guide", false);
        _initBanner();
      } else {
        _initSplash();
      }
    });`

延迟500毫秒就可以确定是同步读取吗？谢谢

**Comment by Sky24n** [comment]
![图片](https://user-images.githubusercontent.com/15412262/58364116-b8855d00-7ee1-11e9-907f-2a61e1c1f199.png)
sp初始化完成才会走后面的逻辑。

**Comment by bjxiaowanzi** [comment]
@Sky24n 所以这个500毫秒延时纯粹是为了延时。是我理解错了，谢谢。
